language: objective-c
osx_image: xcode9.3
install:
  - carthage bootstrap --platform iOS
script:
  - xcodebuild clean test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' -workspace Flint.xcworkspace -scheme FlintCore-iOS CODE_SIGNING_REQUIRED=NO